name: Update README

on:
  schedule:
    # Cambiado a "0 */12 * * *" para que corra cada 12 horas exactas.
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    
    # Damos permiso para modificar los archivos del repositorio
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4 # Mantén checkout actualizado
      
      - uses: Readme-Workflows/recent-activity@main # Cambiar de v2.4.1 a @main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

